### PR TITLE
Description text is now left justified when necessary

### PR DESCRIPTION
**Pull request by MikeWallaceDev**
First off, I wanted to do this in two PRs but I wasn't able to do it, sorry about that.

The first commit is gradle changes. They allow you to include your project as a module in another project.  This allows us to work on the library in a live environment.  I don't believe that they will cause you any problems.

The second commit will change the flow of the description text depending on its length. If the text is displayed in only one line then it will be centered like before.  However if the text is displayed on more than one line then it will be left justified.  This has to be done in the onResume() because the text isn't flowed yet in the onCreate() method.

Also, the code was formatted by AS automatically, that's why the whole file appears as modified. Sorry about that.

### CODE REVIEW

**Comment by chyrta** [comment]
Thank you for a great job, Mike!

**Comment by MikeWallaceDev** [comment]
You're very welcome Chyrta, this is going to help my app a lot, so I'm happy to help :)

Can you please let me know when you push to JCenter so that I can update my build.gradle?

**Comment by MikeWallaceDev** [comment]
Hi Chyrta!
I just added more features.  I was trying to make a second PR but I think that it all got merged into the first PR.  I'm new to PR on GitHub so I'm not really sure what's going on :D 
Anyway, let me know how you want to go about this.  I'm actively using Onboarder now so there may be new code added soon, so I think that it's best that you stay on top of these PRs before I start doing stuff that you don't want in your branch and things become complicated...

**Comment by MikeWallaceDev** [comment]
More features...

**Comment by chyrta** [comment]
Great. When I have time, I'll make a new release and notify your about that.

**Pull request merged**
